In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

### Day 5 — COVID-19, Our World in Data (Time-Series + Rolling Avg)
  - Filter to 2–3 countries, set date as index
  - 7-day rolling average of new cases (`.rolling(7).mean()`)
  - Plot rolling average, compare countries
  - Write takeaway: how waves differed in timing/peak

In [2]:
df = pd.read_csv("DATASETSzip/full_grouped.csv")

In [3]:
df.head()

,Date,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
0,2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean
1,2020-01-22,Albania,0,0,0,0,0,0,0,Europe
2,2020-01-22,Algeria,0,0,0,0,0,0,0,Africa
3,2020-01-22,Andorra,0,0,0,0,0,0,0,Europe
4,2020-01-22,Angola,0,0,0,0,0,0,0,Africa

In [6]:
df.set_index("Date",inplace=True)

In [7]:
df

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
Date,,,,,,,,,
2020-01-22,Afghanistan,0,0,0,0,0,0,0,Eastern Mediterranean
2020-01-22,Albania,0,0,0,0,0,0,0,Europe
2020-01-22,Algeria,0,0,0,0,0,0,0,Africa
2020-01-22,Andorra,0,0,0,0,0,0,0,Europe
2020-01-22,Angola,0,0,0,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...
2020-07-27,West Bank and Gaza,10621,78,3752,6791,152,2,0,Eastern Mediterranean
2020-07-27,Western Sahara,10,1,8,1,0,0,0,Africa
2020-07-27,Yemen,1691,483,833,375,10,4,36,Eastern Mediterranean
2020-07-27,Zambia,4552,140,2815,1597,71,1,465,Africa
2020-07-27,Zimbabwe,2704,36,542,2126,192,2,24,Africa

In [24]:
df[df["Country/Region"].isin(["India","China","Japan"])]

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,WHO Region
Date,,,,,,,,,
2020-01-22,China,548,17,28,503,0,0,0,Western Pacific
2020-01-22,India,0,0,0,0,0,0,0,South-East Asia
2020-01-22,Japan,2,0,0,2,0,0,0,Western Pacific
2020-01-23,China,643,18,30,595,95,1,2,Western Pacific
2020-01-23,India,0,0,0,0,0,0,0,South-East Asia
...,...,...,...,...,...,...,...,...,...
2020-07-26,India,1435616,32771,917568,485277,49981,711,31995,South-East Asia
2020-07-26,Japan,30548,998,21606,7944,864,2,142,Western Pacific
2020-07-27,China,86783,4656,78869,3258,213,4,7,Western Pacific
2020-07-27,India,1480073,33408,951166,495499,44457,637,33598,South-East Asia
2020-07-27,Japan,31142,998,21970,8174,594,0,364,Western Pacific

In [33]:
df['cases_7day_avg'] = df['New cases'].rolling(7).mean()

In [35]:
df[df["Country/Region"]=="China"]['cases_7day_avg'].head()

Date
2020-01-22     0.000000
2020-01-23    13.571429
2020-01-24    39.571429
2020-01-25    69.428571
2020-01-26    95.714286
Name: cases_7day_avg, dtype: float64

In [38]:
df['cases_7day_avg'] = df.groupby('Country/Region')['New cases'].transform(lambda x: x.rolling(7).mean())

In [39]:
df[df["Country/Region"]=="China"]['cases_7day_avg'].head()

Date
2020-01-22   NaN
2020-01-23   NaN
2020-01-24   NaN
2020-01-25   NaN
2020-01-26   NaN
Name: cases_7day_avg, dtype: float64

In [41]:
china_data = df[df["Country/Region"] == "China"].head(10)
china_data[['New cases', 'cases_7day_avg']]

            New cases  cases_7day_avg
Date
2020-01-22          0             NaN
2020-01-23         95             NaN
2020-01-24        277             NaN
2020-01-25        486             NaN
2020-01-26        669             NaN
2020-01-27        802             NaN
2020-01-28       2632      708.714286
2020-01-29        578      791.285714
2020-01-30       2054     1071.142857
2020-01-31       1661     1268.857143